# Generated by Django 6.0.7 on 2026-07-15 09:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("total_turns", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "conversations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[("user", "User"), ("ai", "AI")], max_length=20
                    ),
                ),
                ("turn_number", models.PositiveIntegerField()),
                ("message", models.TextField()),
                ("token_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "messages",
                "ordering": ["turn_number"],
            },
        ),
        migrations.CreateModel(
            name="MessageFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("grammar_correction", models.TextField(blank=True)),
                ("optimized_sentence", models.TextField(blank=True)),
                ("explanation", models.TextField(blank=True)),
                ("next_question", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "message_feedback",
            },
        ),
        migrations.CreateModel(
            name="ConversationState",
            fields=[
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="state",
                        serialize=False,
                        to="conversations.conversation",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("introduction", "Introduction"),
                            ("practice", "Practice"),
                            ("feedback", "Feedback"),
                            ("completed", "Completed"),
                        ],
                        default="introduction",
                        max_length=30,
                    ),
                ),
                ("current_goal", models.TextField(blank=True)),
                ("progress_percentage", models.PositiveSmallIntegerField(default=0)),
                ("conversation_summary", models.TextField(blank=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "conversation_states",
            },
        ),
    ]
