# Generated by Django 6.0.7 on 2026-07-15 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai", "0001_initial"),
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airequest",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_requests",
                to="conversations.conversation",
            ),
        ),
        migrations.AddField(
            model_name="airequest",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requests",
                to="ai.aiprovider",
            ),
        ),
    ]
