# Generated by Django 6.0.7 on 2026-07-16 06:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("topics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VocabularyWord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("word", models.CharField(max_length=100, unique=True)),
                ("definition", models.TextField()),
                ("pronunciation", models.CharField(blank=True, max_length=255)),
                (
                    "part_of_speech",
                    models.CharField(
                        choices=[
                            ("noun", "Noun"),
                            ("verb", "Verb"),
                            ("adjective", "Adjective"),
                            ("adverb", "Adverb"),
                            ("pronoun", "Pronoun"),
                            ("preposition", "Preposition"),
                            ("conjunction", "Conjunction"),
                            ("interjection", "Interjection"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("A1", "A1 - Beginner"),
                            ("A2", "A2 - Elementary"),
                            ("B1", "B1 - Intermediate"),
                            ("B2", "B2 - Upper Intermediate"),
                            ("C1", "C1 - Advanced"),
                            ("C2", "C2 - Proficient"),
                        ],
                        default="A1",
                        max_length=20,
                    ),
                ),
                ("example_sentences", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocabulary_words",
                        to="topics.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vocabulary Word",
                "verbose_name_plural": "Vocabulary Words",
                "db_table": "vocabulary_words",
                "ordering": ["word"],
            },
        ),
        migrations.CreateModel(
            name="UserVocabulary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("times_seen", models.PositiveIntegerField(default=0)),
                ("times_practiced", models.PositiveIntegerField(default=0)),
                ("mastery_level", models.PositiveSmallIntegerField(default=0)),
                ("mastered", models.BooleanField(default=False)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_reviewed", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocabulary",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vocabulary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="vocabulary.vocabularyword",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Vocabulary",
                "verbose_name_plural": "User Vocabulary",
                "db_table": "user_vocabulary",
                "unique_together": {("user", "vocabulary")},
            },
        ),
    ]
