# Generated by Django 6.0.7 on 2026-07-15 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VocabularyWord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("word", models.CharField(max_length=100, unique=True)),
                ("definition", models.TextField()),
                ("pronunciation", models.CharField(blank=True, max_length=255)),
                (
                    "part_of_speech",
                    models.CharField(
                        choices=[
                            ("noun", "Noun"),
                            ("verb", "Verb"),
                            ("adjective", "Adjective"),
                            ("adverb", "Adverb"),
                            ("pronoun", "Pronoun"),
                            ("preposition", "Preposition"),
                            ("conjunction", "Conjunction"),
                            ("interjection", "Interjection"),
                            ("phrase", "Phrase"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("example_sentences", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Vocabulary Word",
                "verbose_name_plural": "Vocabulary Words",
                "db_table": "vocabulary_words",
                "ordering": ["word"],
            },
        ),
        migrations.CreateModel(
            name="UserVocabulary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("times_seen", models.PositiveIntegerField(default=0)),
                ("times_practiced", models.PositiveIntegerField(default=0)),
                ("mastery_level", models.PositiveSmallIntegerField(default=0)),
                ("mastered", models.BooleanField(default=False)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_reviewed", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocabulary",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vocabulary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learners",
                        to="vocabulary.vocabularyword",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Vocabulary",
                "verbose_name_plural": "User Vocabulary",
                "db_table": "user_vocabulary",
                "ordering": ["-last_reviewed", "-first_seen"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "vocabulary"), name="unique_user_vocabulary"
                    )
                ],
            },
        ),
    ]
