# Generated by Django 6.0.7 on 2026-07-16 06:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("topics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("ai_role", models.CharField(max_length=100)),
                ("user_role", models.CharField(max_length=100)),
                ("opening_prompt", models.TextField(blank=True)),
                ("learning_objective", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("A1", "A1 - Beginner"),
                            ("A2", "A2 - Elementary"),
                            ("B1", "B1 - Intermediate"),
                            ("B2", "B2 - Upper Intermediate"),
                            ("C1", "C1 - Advanced"),
                            ("C2", "C2 - Proficient"),
                        ],
                        default="A1",
                        max_length=20,
                    ),
                ),
                ("grammar_focus", models.CharField(blank=True, max_length=100)),
                ("vocabulary_focus", models.TextField(blank=True)),
                ("max_turns", models.PositiveIntegerField(default=10)),
                ("is_system", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_scenarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to="topics.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scenario",
                "verbose_name_plural": "Scenarios",
                "db_table": "scenarios",
                "ordering": ["title"],
            },
        ),
    ]
